### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by QianzhaoJ** [robinweide/GENOVA#228]
Hi:
   I tried to install `GENOVA`  using `install_github("robinweide/GENOVA@v0.95")` and my R version is v4.0.2，but failed.
   Here is the error information:

```
-  preparing 'bigwrig':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'bigwrig_0.1.0.tar.gz'
   
Installing package into ‘C:/Users/JiQianZhao/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'bigwrig' ...
** using staged installation
** libs

*** arch - i386
"C:/rtools40/mingw32/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Users/JiQianZhao/Documents/R/win-library/4.0/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
"C:/rtools40/mingw32/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Users/JiQianZhao/Documents/R/win-library/4.0/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c bigwrig.cpp -o bigwrig.o
In file included from bigWig.h:1,
                 from bigwrig.cpp:4:
io.h:1:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-40~1.2/etc/i386/Makeconf:229: bigwrig.o] Error 1
ERROR: compilation failed for package 'bigwrig'

```

Could you give me some advices?
Thanks in advance !
Best wishes
Qianzhao

**Comment by teunbrand** [comment]
Hi,

I recommend installing the current version of GENOVA instead of the v0.95 version as follows:

```
devtools::install_github("robinweide/GENOVA")
```

If for some legacy reason you would need the older version you could use:

```
devtools::install_github("robinweide/GENOVA@v0.95", dependencies = FALSE)
```

However, the newer version made significant improvements over the older one so I'd like to repeat that it is probably better to install the newer version.

As an aside, if the bigwrig package doesn't compile on R4.02 (which I confirmed on my local Windows machine), we have yet another reason to pursue #118 .

Best wishes

**Comment by QianzhaoJ** [comment]
It works! Thanks a lot.
